### ISSUE TITLE
[RFC] Replace Guzzle with HTTPlug

### ISSUE THREAD

**Issue by kejwmen** [smsapi/smsapi-php-client#78]
Hi.
What do you think about replacing explicit Guzzle dependency with [HTTPlug](https://github.com/php-http/httplug)?

HTTPlug is an http client abstraction meant especially for libraries, to avoid binding to specific implementation so teams using your library can choose their favorite implementation without risk of getting version conflicts. 
So it makes life easier.

I can prepare a PR, but wanted to ask first.

**Comment by sudlik** [comment]
Hello,

We are happy to see you RFC. It's great idea to make _SMSAPI PHP Client_ more dependency-independent, but our team discussed about it and we are decided to use [PSR-18](https://github.com/php-fig/fig-standards/tree/master/proposed/http-client/) instead of _HTTPlug_. _PSR-18_ is still in review stage, but we think there shouldn't be any break of backward compatibility. Considering the above I believe it's not worth implementing _HTTPlug_. However, if you are still eager to be involved in development of _SMSAPI PHP Client_ we are happy to see your PR for _PSR-18_.

Please, be aware that we are going to release _v2_ in few weeks.

**Comment by kejwmen** [comment]
Nice, great to see that PSR-18 is alive!

I did some basic research about available implementations, and we have 2:
- HTTPlug (2.0 will be PSR-18 compliant)
- Buzz

And we need to choose one for tests, and give library users some tips about migration. Because they will have to choose something from [this list](https://packagist.org/providers/php-http/client-implementation).

HTTPlug will make it easy because of existing guzzle adapter. 
It's not stable yet, but [they want to release 2.0 this month](https://github.com/php-http/httplug/issues/139). Coincidence? 😄 
So this would be recommended implementation for guzzle users. 

I will do my best to prepare PR as soon as possible, so we can merge it before v2 of your library, after HTTPlug 2.0 is stable.

What do you think?

**Comment by sudlik** [comment]
I agree with you, HTTPlug 2.0 it's good choice.

We will wait for your PR.
